### ISSUE TITLE
Investigate why index.yaml doesn't autogenerate all indexes needed

### ISSUE THREAD

**Issue by terinpw** [Recidiviz/recidiviz-data#389]
Encountered this issue during the infer_release flow:

```
NeedIndexError: no matching index found. recommended index is:
- kind: ScrapeSession
 properties:
 - name: region
 - name: start
   direction: desc
```

Index.yaml should be auto generated. For now we added a manual index in PR #388, but we should investigate why the index wasn't auto generated.
